# Generated by Django 4.2.4 on 2023-08-25 08:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0002_account_account_cs'),
    ]

    operations = [
        migrations.RenameField(
            model_name='account_cs',
            old_name='verify_1',
            new_name='verify_RFID',
        ),
        migrations.RenameField(
            model_name='account_cs',
            old_name='verify_2',
            new_name='verify_gesture',
        ),
        migrations.RenameField(
            model_name='account_cs',
            old_name='verify_3',
            new_name='verify_password',
        ),
        migrations.RemoveField(
            model_name='account_cs',
            name='verify_4',
        ),
    ]
